### ISSUE TITLE
云端备份

### ISSUE THREAD

**Issue by yimo0908** [wbsdty331/FFXIVBackupTool#1]
可不可以增加云端备份功能，上传到自己的GitHub仓库

**Comment by wbsdty331** [comment]
有时间了看看能不能做吧

**Comment by namoen0301** [comment]
想了一下云端备份需要做的：
用户在程序里登录GitHub授权这个应用，选择自己的仓库，然后将打包好的东西push到仓库里面去
这套东西理论上是完全可行的，就是难度有点大，后面再说

**Comment by namoen0301** [comment]
1.0.4已加入OneDrive云端备份功能（实验性，不稳定）
